import { supabase } from "@/integrations/supabase/client";

/**
 * Packing-slip lines often come from PO lines that were typed free-hand and have
 * no product_id. Without a product we can't move inventory, so resolve (or create)
 * a catalog product from the line's part number / description.
 */
export async function resolveProductId(opts: {
  productId?: string | null;
  partNumber?: string | null;
  description: string;
  unit?: string | null;
}): Promise<string | null> {
  if (opts.productId) return opts.productId;
  const key = (opts.partNumber || opts.description || "").trim();
  if (!key) return null;

  const { data: existing } = await supabase
    .from("products")
    .select("id")
    .or(`part_number.ilike.${key},description.ilike.${key}`)
    .limit(1)
    .maybeSingle();
  if (existing?.id) return existing.id;

  const { data: created, error } = await supabase
    .from("products")
    .insert({
      part_number: key,
      description: opts.description || key,
      unit: opts.unit || "ea",
    })
    .select("id")
    .single();
  if (error) throw error;
  return created.id;
}

export type SlipInventoryLine = {
  product_id: string | null;
  qty_received: number;
};

/** Replace all inventory movements generated by a packing slip with the given lines. */
export async function syncSlipInventory(params: {
  slipId: string;
  slipNumber: string;
  projectId: string;
  lines: SlipInventoryLine[];
  userId: string | null;
}) {
  await supabase
    .from("inventory_adjustments")
    .delete()
    .eq("source_type", "packing_slip")
    .eq("source_id", params.slipId);

  const rows = params.lines
    .filter((l) => l.product_id && l.qty_received > 0)
    .map((l) => ({
      project_id: params.projectId,
      product_id: l.product_id!,
      delta: l.qty_received,
      source_type: "packing_slip" as const,
      source_id: params.slipId,
      reason: `Received on slip ${params.slipNumber}`,
      created_by: params.userId,
    }));

  if (rows.length > 0) {
    const { error } = await supabase.from("inventory_adjustments").insert(rows);
    if (error) throw error;
  }
}

export function slipStatusFor(lines: { qty_ordered: number; qty_received: number }[]): "received" | "partially_received" {
  return lines.some((l) => l.qty_received < l.qty_ordered) ? "partially_received" : "received";
}

/** Recompute a PO's received status from every packing slip logged against it. */
export async function refreshPoStatus(poId: string) {
  const [{ data: poItems }, { data: slipItems }] = await Promise.all([
    supabase.from("purchase_order_items").select("id, qty").eq("po_id", poId),
    supabase
      .from("packing_slip_items")
      .select("po_item_id, qty_received, packing_slips!inner(po_id)")
      .eq("packing_slips.po_id", poId),
  ]);
  const received = new Map<string, number>();
  (slipItems ?? []).forEach((s) => {
    if (!s.po_item_id) return;
    received.set(s.po_item_id, (received.get(s.po_item_id) ?? 0) + Number(s.qty_received));
  });
  const anyOpen = (poItems ?? []).some((i) => (received.get(i.id) ?? 0) < Number(i.qty));
  await supabase
    .from("purchase_orders")
    .update({ status: anyOpen ? "partially_received" : "received" })
    .eq("id", poId);
}
