-- ============================================================
-- MKJ OPS APP — DEMO DATA TEARDOWN
-- ============================================================
-- Removes everything seed_demo_data.sql added, and nothing else. Run this
-- once MKJ is done with the walkthrough (approved or rejected).
--
-- Every DELETE below matches ONLY the "(DEMO) " / "DEMO-" markers that
-- seed_demo_data.sql wrote — no real project, product, supplier, PO, slip,
-- ticket, borrow request, or notification can match these patterns, so
-- this cannot touch real data. Run it the same way as the seed script:
-- paste into the Supabase SQL Editor and run once.
--
-- Order matters (children before parents, and inventory_adjustments before
-- the packing slips/tickets/borrow requests it points at, since it's
-- looked up by matching those rows' markers before they're removed).
-- purchase_order_items / packing_slip_items / shipping_ticket_items /
-- purchase_order_pdfs / shipping_ticket_pdfs all cascade automatically
-- from their parent row and don't need their own DELETE.
--
-- NOT handled here (see README.md "After teardown"): the one placeholder
-- proof-of-delivery image you may have uploaded to the private
-- shipping-ticket-proofs bucket while completing the manual "mark
-- delivered" step. Deleting the ticket row below makes it unreachable from
-- the app either way, but removing the file itself from Storage is a
-- one-click cleanup in the Supabase dashboard, not something to do with a
-- raw SQL DELETE against storage.objects.
-- ============================================================

BEGIN;

-- 1. Inventory ledger rows — both the hand-seeded opening balances and
--    every row the RPCs generated for demo packing slips / shipping
--    tickets / borrow requests (found via those rows' markers, so this
--    must run before they're deleted below).
DELETE FROM public.inventory_adjustments
WHERE reason LIKE '(DEMO)%'
   OR source_id IN (SELECT id FROM public.packing_slips WHERE notes LIKE '(DEMO)%')
   OR source_id IN (SELECT id FROM public.shipping_tickets WHERE deliver_to_name LIKE '(DEMO)%')
   OR source_id IN (SELECT id FROM public.borrow_requests WHERE reason LIKE '(DEMO)%');

-- 2. Notifications generated by the borrow-request trigger. Every one of
--    them mentions a DEMO- product part number in its body.
DELETE FROM public.notifications WHERE body LIKE '%DEMO-%';

-- 3. Packing slips (cascades packing_slip_items). Must run before step 6
--    (purchase_orders) — packing_slips.po_id is ON DELETE RESTRICT.
DELETE FROM public.packing_slips WHERE notes LIKE '(DEMO)%';

-- 4. Shipping tickets (cascades shipping_ticket_items, shipping_ticket_pdfs).
DELETE FROM public.shipping_tickets WHERE deliver_to_name LIKE '(DEMO)%';

-- 5. Borrow requests.
DELETE FROM public.borrow_requests WHERE reason LIKE '(DEMO)%';

-- 6. Purchase orders (cascades purchase_order_items, purchase_order_pdfs).
DELETE FROM public.purchase_orders
WHERE supplier_id IN (SELECT id FROM public.suppliers WHERE name LIKE '(DEMO)%');

-- 7. Products.
DELETE FROM public.products WHERE part_number LIKE 'DEMO-%';

-- 8. Suppliers.
DELETE FROM public.suppliers WHERE name LIKE '(DEMO)%';

COMMIT;

-- ============================================================
-- Sanity check — should return zero rows for every one of these:
--   select * from products where part_number like 'DEMO-%';
--   select * from suppliers where name like '(DEMO)%';
--   select * from purchase_orders where description like '(DEMO)%';
--   select * from packing_slips where notes like '(DEMO)%';
--   select * from shipping_tickets where deliver_to_name like '(DEMO)%';
--   select * from borrow_requests where reason like '(DEMO)%';
--   select * from inventory_adjustments where reason like '(DEMO)%';
--   select * from notifications where body like '%DEMO-%';
-- ============================================================
